language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: jnzY4aYqX5wT/hQVOCYQFqz+UiegeY8dmAdP9sOz/yt2TaBBT02ChSlpyvT8GqyFpibf/w5Nn5feGcQrvyzgf6gTIsOf8Zja9TMWcGors6VIksrlkcFGgg6ITKGYjFugFmYtsSU3J5CBEP5YSu+x6tGcTmHqeqIfNBvATk1MTX9q71E86kpdp0V/cr37CeEPTnD6dGGqruhDylkolfJNaOomRcwVVLz6SHykRacmDpk2lDoxBs4pgbOhTsfBjPAPeg2tQ5thx/aqKv8lTINUY0duKmRb++N6lp0uUlv3uyZX3o2+KNpcytyPqCSCxzEpWe4MOjTRtpZYtQh2hVvPcAK65oJFQJBmiqlYH5uIgOA8upLVytLZaTj3lPPet+YiA4uDqB9HDNzlhHXnQ4+xLPqzS5HmSnsgWsRsSpMTRT/lnEfMcPzhlJ7zTx2TS489JfZqhwzzqXNdFgiLrZPLP9MZ/wvh4oRU12XbrqAMXQfV+bF5QoCyoDR5wRmel52BRtSKI9EO5/FaL7y/TWpDGdfoREoEVR28aTj0F2HDSg8MuJrkk4jTNNnCVMA+ypwtpotyusYxNc8D0xyzA/4aZY841KNoFZ769LUf/Jf6EFZ/wwZmRHedu/i9AW6I156e4OYwSdsmRr4xaVTcH7RXJ9AsETfn0mhPn87ulUu8vQ==
  app: rocky-ocean-66571